version: '3.7'

services:
  integration:
    image: graph-jira-app
    build: .
    container_name: graph-jira-app
    volumes:
      - .:/app:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      GRAPH_DB_ENDPOINT: graph
      JIRA_LOCAL_EXECUTION_USERNAME: 'YOUR JIRA LOGIN HERE'
      JIRA_LOCAL_EXECUTION_PASSWORD: 'YOUR JIRA PASSWORD HERE'
      JIRA_LOCAL_EXECUTION_HOST: ''
    depends_on:
      - graph
  graph:
    image: tinkerpop/gremlin-server:3.3
    restart: unless-stopped
    ports:
      - "8182:8182"
